### ISSUE TITLE
update to 1.21.1 pls

### ISSUE THREAD

**Issue by Dinith21** [GeeTransit/audaki-linkart-compat#1]

**Comment by SuperLlama88888** [comment]
Hi, I'd also like to use this mod in 1.21, but I lack the technical expertise to.

Thank you for your time!

**Comment by SuperLlama88888** [comment]
Hi, I've forked Audaki Cart Engine and added these commits onto it such that this is now updated to 1.21.

[Here's the release.](https://github.com/SuperLlama88888/minecraft-cart-engine/releases/tag/vf7636ab43d7c330d781e9e762e135bb02784d390)

**Comment by Dinith21** [comment]
Thanks!
